# Base image
FROM node:latest

# Create app directory
WORKDIR /app

# Install nmap
RUN apt update -y
RUN apt install nmap -y

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Bundle app source
COPY . .

RUN npm i -g pnpm typescript
# Install app dependencies
RUN pnpm install

# Build
RUN pnpm build

# Exposing server port
EXPOSE 3001

# Start the server using the production build
CMD [ "pnpm", "start" ]

